<a href="https://colab.research.google.com/github/Bast1-py/Breast-Cancer-Prediction-WebApp/blob/master/001_model_building(breast_cancer).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install -q catboost

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from catboost import CatBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
dataset_url = 'https://raw.githubusercontent.com/apogiatzis/breast-cancer-azure-ml-notebook/master/breast-cancer-data.csv'
df = pd.read_csv(dataset_url)
df.head(35)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.990,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.71190,0.26540,0.4601,0.11890,NaN
1,842517,M,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.24160,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.45040,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.420,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.68690,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.40000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.450,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.53550,0.17410,0.3985,0.12440,NaN
6,844359,M,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.37840,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.710,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.26780,0.15560,0.3196,0.11510,NaN
8,844981,M,13.000,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.53900,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.460,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.10500,0.22100,0.4366,0.20750,NaN
10,845636,M,16.020,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.03323,...,33.88,123.80,1150.0,0.1181,0.1551,0.14590,0.09975,0.2948,0.08452,NaN
11,84610002,M,15.780,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.06606,...,27.28,136.50,1299.0,0.1396,0.5609,0.39650,0.18100,0.3792,0.10480,NaN
12,846226,M,19.170,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.11180,...,29.94,151.70,1332.0,0.1037,0.3903,0.36390,0.17670,0.3176,0.10230,NaN
13,846381,M,15.850,23.95,103.70,782.7,0.08401,0.10020,0.09938,0.05364,...,27.66,112.00,876.5,0.1131,0.1924,0.23220,0.11190,0.2809,0.06287,NaN
14,84667401,M,13.730,22.61,93.60,578.3,0.11310,0.22930,0.21280,0.08025,...,32.01,108.80,697.7,0.1651,0.7725,0.69430,0.22080,0.3596,0.14310,NaN
15,84799002,M,14.540,27.54,96.73,658.8,0.11390,0.15950,0.16390,0.07364,...,37.13,124.10,943.2,0.1678,0.6577,0.70260,0.17120,0.4218,0.13410,NaN
16,848406,M,14.680,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.05259,...,30.88,123.40,1138.0,0.1464,0.1871,0.29140,0.16090,0.3029,0.08216,NaN
17,84862001,M,16.130,20.68,108.10,798.8,0.11700,0.20220,0.17220,0.10280,...,31.48,136.80,1315.0,0.1789,0.4233,0.47840,0.20730,0.3706,0.11420,NaN
18,849014,M,19.810,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.09498,...,30.88,186.80,2398.0,0.1512,0.3150,0.53720,0.23880,0.2768,0.07615,NaN
19,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,...,19.26,99.70,711.2,0.1440,0.1773,0.23900,0.12880,0.2977,0.07259,NaN
20,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.03110,...,20.49,96.09,630.5,0.1312,0.2776,0.18900,0.07283,0.3184,0.08183,NaN
21,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.02076,...,15.66,65.13,314.9,0.1324,0.1148,0.08867,0.06227,0.2450,0.07773,NaN
22,8511133,M,15.340,14.26,102.50,704.4,0.10730,0.21350,0.20770,0.09756,...,19.08,125.10,980.9,0.1390,0.5954,0.63050,0.23930,0.4667,0.09946,NaN
23,851509,M,21.160,23.04,137.20,1404.0,0.09428,0.10220,0.10970,0.08632,...,35.59,188.00,2615.0,0.1401,0.2600,0.31550,0.20090,0.2822,0.07526,NaN
24,852552,M,16.650,21.38,110.00,904.6,0.11210,0.14570,0.15250,0.09170,...,31.56,177.00,2215.0,0.1805,0.3578,0.46950,0.20950,0.3613,0.09564,NaN
25,852631,M,17.140,16.40,116.00,912.7,0.11860,0.22760,0.22290,0.14010,...,21.40,152.40,1461.0,0.1545,0.3949,0.38530,0.25500,0.4066,0.10590,NaN
26,852763,M,14.580,21.53,97.41,644.8,0.10540,0.18680,0.14250,0.08783,...,33.21,122.40,896.9,0.1525,0.6643,0.55390,0.27010,0.4264,0.12750,NaN
27,852781,M,18.610,20.25,122.10,1094.0,0.09440,0.10660,0.14900,0.07731,...,27.26,139.90,1403.0,0.1338,0.2117,0.34460,0.14900,0.2341,0.07421,NaN
28,852973,M,15.300,25.27,102.40,732.4,0.10820,0.16970,0.16830,0.08751,...,36.71,149.30,1269.0,0.1641,0.6110,0.63350,0.20240,0.4027,0.09876,NaN
29,853201,M,17.570,15.05,115.00,955.1,0.09847,0.11570,0.09875,0.07953,...,19.52,134.90,1227.0,0.1255,0.2812,0.24890,0.14560,0.2756,0.07919,NaN
30,853401,M,18.630,25.11,124.80,1088.0,0.10640,0.18870,0.23190,0.12440,...,34.01,160.50,1670.0,0.1491,0.4257,0.61330,0.18480,0.3444,0.09782,NaN
31,853612,M,11.840,18.70,77.93,440.6,0.11090,0.15160,0.12180,0.05182,...,28.12,119.40,888.7,0.1637,0.5775,0.69560,0.15460,0.4761,0.14020,NaN
32,85382601,M,17.020,23.98,112.80,899.3,0.11970,0.14960,0.24170,0.12030,...,32.09,136.10,1344.0,0.1634,0.3559,0.55880,0.18470,0.3530,0.08482,NaN
33,854002,M,19.270,26.47,127.90,1162.0,0.09401,0.17190,0.16570,0.07593,...,30.90,161.40,1813.0,0.1509,0.6590,0.60910,0.17850,0.3672,0.11230,NaN
34,854039,M,16.130,17.88,107.00,807.2,0.10400,0.15590,0.13540,0.07752,...,27.26,132.70,1261.0,0.1446,0.5804,0.52740,0.18640,0.4270,0.12330,NaN

In [ ]:
# label encoding
# M = Malignant; B = Benign
df['diagnosis'] = df['diagnosis'].map(
    {
        'M': 1,
        'B': 0
    }
)

In [ ]:
df.diagnosis.value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [ ]:
features = [
    'radius_mean', 'texture_mean', 'perimeter_mean',
    'smoothness_mean', 'compactness_mean'
]

X=df[features]
y=df.diagnosis
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.19)

In [ ]:
len(X_train)

460

In [ ]:
len(X_test)

109

# **Model Building**

## **Random Forest Model**

In [ ]:
model_rf = RandomForestClassifier(
    n_estimators=250, n_jobs=1, random_state=42
)

model_rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=250, n_jobs=1, random_state=42)

In [ ]:
model_prediction_rf = model_rf.predict(X_test)
print('Accuracy Score Random Forest Model is: ', round(accuracy_score(model_prediction_rf, y_test)*100,2),'%')

Accuracy Score Random Forest Model is:  90.83 %

## **Support Vector Machine Model**

In [ ]:
model_svm = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale'
)

model_svm.fit(X_train, y_train)

SVC()

In [ ]:
model_prediction_svm = model_svm.predict(X_test)
print('Accuracy Score Support Vector Machine model is: ', round(accuracy_score(model_prediction_svm, y_test)*100, 2),'%')

Accuracy Score Support Vector Machine model is:  85.32 %

## **Decision Tree Model**

In [ ]:
model_dt = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)
model_dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [ ]:
model_prediction_dt = model_dt.predict(X_test)
print('Accuracy Score Decision Tree Model is: ', round(accuracy_score(model_prediction_dt, y_test)*100,2),'%')

Accuracy Score Decision Tree Model is:  88.07 %

## **AdaBoost Classifier**

In [ ]:
model_ab = AdaBoostClassifier(
    estimator=model_dt, n_estimators=100,
    random_state=42
)

model_ab.fit(X_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=3,
                                                    random_state=42),
                   n_estimators=100, random_state=42)

In [ ]:
model_prediction_ab = model_ab.predict(X_test)
print('Accuracy Score AdaBoost Model is:', round(accuracy_score(model_prediction_ab, y_test)*100,2),'%')

Accuracy Score AdaBoost Model is: 93.58 %

## **CatBoost Model**

In [ ]:
model_cb = CatBoostClassifier(
    iterations=400, learning_rate=0.1, depth=3
)

model_cb.fit(X_train, y_train)

0:	learn: 0.5810036	total: 51.7ms	remaining: 20.6s
1:	learn: 0.5019921	total: 52.7ms	remaining: 10.5s
2:	learn: 0.4328359	total: 55.9ms	remaining: 7.39s
3:	learn: 0.3853041	total: 56.9ms	remaining: 5.63s
4:	learn: 0.3488337	total: 58.1ms	remaining: 4.59s
5:	learn: 0.3190681	total: 60.2ms	remaining: 3.95s
6:	learn: 0.2904229	total: 61.2ms	remaining: 3.43s
7:	learn: 0.2661425	total: 65.3ms	remaining: 3.2s
8:	learn: 0.2492991	total: 66.3ms	remaining: 2.88s
9:	learn: 0.2404945	total: 67.9ms	remaining: 2.65s
10:	learn: 0.2314986	total: 70.9ms	remaining: 2.51s
11:	learn: 0.2186337	total: 72ms	remaining: 2.33s
12:	learn: 0.2026402	total: 75.1ms	remaining: 2.24s
13:	learn: 0.1922588	total: 78.2ms	remaining: 2.16s
14:	learn: 0.1855630	total: 79.2ms	remaining: 2.03s
15:	learn: 0.1794453	total: 82.4ms	remaining: 1.98s
16:	learn: 0.1762071	total: 83.5ms	remaining: 1.88s
17:	learn: 0.1709312	total: 84.5ms	remaining: 1.79s
18:	learn: 0.1668288	total: 89.1ms	remaining: 1.79s
19:	learn: 0.1620251	total: 93.3ms	remaining: 1.77s
20:	learn: 0.1588200	total: 94.5ms	remaining: 1.7s
21:	learn: 0.1550397	total: 97.9ms	remaining: 1.68s
22:	learn: 0.1528476	total: 101ms	remaining: 1.65s
23:	learn: 0.1515546	total: 102ms	remaining: 1.6s
24:	learn: 0.1484908	total: 105ms	remaining: 1.58s
25:	learn: 0.1466753	total: 106ms	remaining: 1.53s
26:	learn: 0.1450386	total: 109ms	remaining: 1.5s
27:	learn: 0.1435931	total: 110ms	remaining: 1.46s
28:	learn: 0.1422408	total: 113ms	remaining: 1.44s
29:	learn: 0.1405329	total: 116ms	remaining: 1.43s
30:	learn: 0.1383466	total: 121ms	remaining: 1.44s
31:	learn: 0.1371196	total: 122ms	remaining: 1.4s
32:	learn: 0.1354145	total: 126ms	remaining: 1.4s
33:	learn: 0.1344234	total: 127ms	remaining: 1.36s
34:	learn: 0.1323629	total: 133ms	remaining: 1.39s
35:	learn: 0.1309565	total: 135ms	remaining: 1.37s
36:	learn: 0.1297184	total: 136ms	remaining: 1.34s
37:	learn: 0.1285284	total: 139ms	remaining: 1.33s
38:	learn: 0.1271026	total: 140ms	remaining: 1.3s
39:	learn: 0.1258850	total: 143ms	remaining: 1.29s
40:	learn: 0.1245490	total: 147ms	remaining: 1.28s
41:	learn: 0.1236462	total: 148ms	remaining: 1.26s
42:	learn: 0.1223122	total: 151ms	remaining: 1.25s
43:	learn: 0.1217903	total: 154ms	remaining: 1.24s
44:	learn: 0.1192673	total: 157ms	remaining: 1.24s
45:	learn: 0.1185743	total: 158ms	remaining: 1.21s
46:	learn: 0.1181319	total: 159ms	remaining: 1.19s
47:	learn: 0.1167691	total: 164ms	remaining: 1.2s
48:	learn: 0.1142395	total: 165ms	remaining: 1.18s
49:	learn: 0.1132905	total: 170ms	remaining: 1.19s
50:	learn: 0.1123649	total: 171ms	remaining: 1.17s
51:	learn: 0.1112045	total: 172ms	remaining: 1.15s
52:	learn: 0.1101706	total: 177ms	remaining: 1.16s
53:	learn: 0.1094086	total: 180ms	remaining: 1.16s
54:	learn: 0.1086908	total: 183ms	remaining: 1.15s
55:	learn: 0.1081684	total: 190ms	remaining: 1.17s
56:	learn: 0.1069420	total: 194ms	remaining: 1.17s
57:	learn: 0.1062635	total: 197ms	remaining: 1.16s
58:	learn: 0.1054808	total: 202ms	remaining: 1.17s
59:	learn: 0.1038555	total: 203ms	remaining: 1.15s
60:	learn: 0.1027290	total: 207ms	remaining: 1.15s
61:	learn: 0.1021404	total: 214ms	remaining: 1.16s
62:	learn: 0.1012095	total: 215ms	remaining: 1.15s
63:	learn: 0.1001617	total: 220ms	remaining: 1.15s
64:	learn: 0.0993106	total: 221ms	remaining: 1.14s
65:	learn: 0.0977630	total: 226ms	remaining: 1.14s
66:	learn: 0.0967168	total: 231ms	remaining: 1.15s
67:	learn: 0.0957082	total: 235ms	remaining: 1.15s
68:	learn: 0.0936683	total: 236ms	remaining: 1.13s
69:	learn: 0.0930817	total: 237ms	remaining: 1.12s
70:	learn: 0.0926539	total: 238ms	remaining: 1.1s
71:	learn: 0.0918461	total: 243ms	remaining: 1.11s
72:	learn: 0.0907573	total: 244ms	remaining: 1.09s
73:	learn: 0.0901027	total: 253ms	remaining: 1.11s
74:	learn: 0.0898551	total: 258ms	remaining: 1.12s
75:	learn: 0.0887296	total: 259ms	remaining: 1.1s
76:	learn: 0.0884074	total: 262ms	remaining: 1.1s
77:	learn: 0.0880174	total: 265ms	remaining: 1.09s
78:	learn: 0.0870016	total: 266ms	remaining: 1.08s
79:	learn: 0.0863672	total: 269ms	remaining: 1.08s
80:	learn: 0.0858705	total: 270ms	remaining: 1.06s
81:	learn: 0.0857016	total: 273ms	remaining: 1.06s
82:	learn: 0.0848543	total: 274ms	remaining: 1.05s
83:	learn: 0.0836828	total: 275ms	remaining: 1.03s
84:	learn: 0.0833532	total: 277ms	remaining: 1.03s
85:	learn: 0.0826353	total: 278ms	remaining: 1.01s
86:	learn: 0.0818408	total: 282ms	remaining: 1.01s
87:	learn: 0.0810915	total: 283ms	remaining: 1s
88:	learn: 0.0808996	total: 286ms	remaining: 1000ms
89:	learn: 0.0804906	total: 287ms	remaining: 989ms
90:	learn: 0.0803416	total: 290ms	remaining: 985ms
91:	learn: 0.0788651	total: 292ms	remaining: 978ms
92:	learn: 0.0781629	total: 293ms	remaining: 968ms
93:	learn: 0.0773962	total: 296ms	remaining: 965ms
94:	learn: 0.0772240	total: 298ms	remaining: 958ms
95:	learn: 0.0767493	total: 301ms	remaining: 955ms
96:	learn: 0.0760476	total: 302ms	remaining: 945ms
97:	learn: 0.0754213	total: 305ms	remaining: 941ms
98:	learn: 0.0749580	total: 308ms	remaining: 938ms
99:	learn: 0.0744111	total: 310ms	remaining: 929ms
100:	learn: 0.0740402	total: 314ms	remaining: 931ms
101:	learn: 0.0734110	total: 315ms	remaining: 921ms
102:	learn: 0.0723100	total: 317ms	remaining: 915ms
103:	learn: 0.0719093	total: 319ms	remaining: 909ms
104:	learn: 0.0714637	total: 322ms	remaining: 906ms
105:	learn: 0.0712945	total: 323ms	remaining: 897ms
106:	learn: 0.0708178	total: 324ms	remaining: 888ms
107:	learn: 0.0700872	total: 329ms	remaining: 890ms
108:	learn: 0.0697544	total: 332ms	remaining: 886ms
109:	learn: 0.0695516	total: 333ms	remaining: 877ms
110:	learn: 0.0690967	total: 337ms	remaining: 877ms
111:	learn: 0.0686230	total: 340ms	remaining: 874ms
112:	learn: 0.0677559	total: 341ms	remaining: 866ms
113:	learn: 0.0672409	total: 344ms	remaining: 864ms
114:	learn: 0.0668122	total: 345ms	remaining: 856ms
115:	learn: 0.0663335	total: 348ms	remaining: 853ms
116:	learn: 0.0657482	total: 351ms	remaining: 850ms
117:	learn: 0.0649091	total: 352ms	remaining: 842ms
118:	learn: 0.0647447	total: 355ms	remaining: 839ms
119:	learn: 0.0643862	total: 356ms	remaining: 832ms
120:	learn: 0.0634454	total: 359ms	remaining: 829ms
121:	learn: 0.0625767	total: 361ms	remaining: 823ms
122:	learn: 0.0622976	total: 365ms	remaining: 823ms
123:	learn: 0.0620556	total: 367ms	remaining: 818ms
124:	learn: 0.0611440	total: 368ms	remaining: 811ms
125:	learn: 0.0607482	total: 372ms	remaining: 810ms
126:	learn: 0.0603714	total: 373ms	remaining: 803ms
127:	learn: 0.0601387	total: 376ms	remaining: 798ms
128:	learn: 0.0594546	total: 379ms	remaining: 795ms
129:	learn: 0.0590189	total: 381ms	remaining: 791ms
130:	learn: 0.0586323	total: 384ms	remaining: 788ms
131:	learn: 0.0581371	total: 385ms	remaining: 781ms
132:	learn: 0.0576685	total: 391ms	remaining: 785ms
133:	learn: 0.0574621	total: 404ms	remaining: 802ms
134:	learn: 0.0573488	total: 405ms	remaining: 795ms
135:	learn: 0.0572446	total: 410ms	remaining: 797ms
136:	learn: 0.0571025	total: 418ms	remaining: 803ms
137:	learn: 0.0564109	total: 424ms	remaining: 805ms
138:	learn: 0.0559982	total: 427ms	remaining: 802ms
139:	learn: 0.0556132	total: 428ms	remaining: 796ms
140:	learn: 0.0552720	total: 433ms	remaining: 796ms
141:	learn: 0.0550306	total: 444ms	remaining: 806ms
142:	learn: 0.0545285	total: 449ms	remaining: 806ms
143:	learn: 0.0541577	total: 450ms	remaining: 800ms
144:	learn: 0.0538707	total: 461ms	remaining: 810ms
145:	learn: 0.0535184	total: 462ms	remaining: 803ms
146:	learn: 0.0530056	total: 469ms	remaining: 807ms
147:	learn: 0.0524131	total: 470ms	remaining: 800ms
148:	learn: 0.0522797	total: 471ms	remaining: 793ms
149:	learn: 0.0518702	total: 478ms	remaining: 797ms
150:	learn: 0.0516587	total: 479ms	remaining: 790ms
151:	learn: 0.0513185	total: 485ms	remaining: 792ms
152:	learn: 0.0506477	total: 491ms	remaining: 793ms
153:	learn: 0.0503324	total: 499ms	remaining: 797ms
154:	learn: 0.0500663	total: 502ms	remaining: 793ms
155:	learn: 0.0499088	total: 509ms	remaining: 796ms
156:	learn: 0.0495035	total: 510ms	remaining: 789ms
157:	learn: 0.0490387	total: 523ms	remaining: 800ms
158:	learn: 0.0486412	total: 524ms	remaining: 794ms
159:	learn: 0.0482965	total: 529ms	remaining: 793ms
160:	learn: 0.0478582	total: 534ms	remaining: 793ms
161:	learn: 0.0475653	total: 535ms	remaining: 786ms
162:	learn: 0.0475397	total: 542ms	remaining: 788ms
163:	learn: 0.0474379	total: 543ms	remaining: 782ms
164:	learn: 0.0470931	total: 544ms	remaining: 775ms
165:	learn: 0.0466153	total: 549ms	remaining: 774ms
166:	learn: 0.0463492	total: 550ms	remaining: 768ms
167:	learn: 0.0458706	total: 555ms	remaining: 767ms
168:	learn: 0.0453568	total: 560ms	remaining: 766ms
169:	learn: 0.0452722	total: 561ms	remaining: 759ms
170:	learn: 0.0449727	total: 564ms	remaining: 756ms
171:	learn: 0.0448159	total: 565ms	remaining: 749ms
172:	learn: 0.0444344	total: 568ms	remaining: 746ms
173:	learn: 0.0442442	total: 569ms	remaining: 740ms
174:	learn: 0.0440960	total: 572ms	remaining: 736ms
175:	learn: 0.0438311	total: 573ms	remaining: 730ms
176:	learn: 0.0436562	total: 574ms	remaining: 724ms
177:	learn: 0.0434200	total: 577ms	remaining: 720ms
178:	learn: 0.0432799	total: 578ms	remaining: 714ms
179:	learn: 0.0430378	total: 581ms	remaining: 711ms
180:	learn: 0.0428550	total: 582ms	remaining: 705ms
181:	learn: 0.0425857	total: 586ms	remaining: 701ms
182:	learn: 0.0422222	total: 589ms	remaining: 698ms
183:	learn: 0.0419882	total: 590ms	remaining: 692ms
184:	learn: 0.0418507	total: 593ms	remaining: 689ms
185:	learn: 0.0414256	total: 594ms	remaining: 683ms
186:	learn: 0.0413736	total: 597ms	remaining: 680ms
187:	learn: 0.0412064	total: 600ms	remaining: 677ms
188:	learn: 0.0410014	total: 601ms	remaining: 671ms
189:	learn: 0.0407841	total: 604ms	remaining: 668ms
190:	learn: 0.0406177	total: 605ms	remaining: 662ms
191:	learn: 0.0403886	total: 608ms	remaining: 659ms
192:	learn: 0.0403080	total: 613ms	remaining: 658ms
193:	learn: 0.0399358	total: 614ms	remaining: 652ms
194:	learn: 0.0397794	total: 619ms	remaining: 651ms
195:	learn: 0.0392751	total: 620ms	remaining: 646ms
196:	learn: 0.0392297	total: 626ms	remaining: 645ms
197:	learn: 0.0389644	total: 629ms	remaining: 641ms
198:	learn: 0.0385279	total: 630ms	remaining: 636ms
199:	learn: 0.0382818	total: 633ms	remaining: 633ms
200:	learn: 0.0378657	total: 634ms	remaining: 627ms
201:	learn: 0.0376649	total: 637ms	remaining: 624ms
202:	learn: 0.0375622	total: 638ms	remaining: 619ms
203:	learn: 0.0373597	total: 641ms	remaining: 616ms
204:	learn: 0.0371804	total: 644ms	remaining: 612ms
205:	learn: 0.0368940	total: 645ms	remaining: 607ms
206:	learn: 0.0368296	total: 648ms	remaining: 604ms
207:	learn: 0.0367269	total: 649ms	remaining: 599ms
208:	learn: 0.0364828	total: 652ms	remaining: 596ms
209:	learn: 0.0361503	total: 653ms	remaining: 591ms
210:	learn: 0.0360983	total: 656ms	remaining: 587ms
211:	learn: 0.0359596	total: 657ms	remaining: 582ms
212:	learn: 0.0356737	total: 658ms	remaining: 577ms
213:	learn: 0.0355442	total: 665ms	remaining: 578ms
214:	learn: 0.0355025	total: 666ms	remaining: 573ms
215:	learn: 0.0351699	total: 673ms	remaining: 573ms
216:	learn: 0.0350563	total: 680ms	remaining: 574ms
217:	learn: 0.0346964	total: 681ms	remaining: 569ms
218:	learn: 0.0344178	total: 686ms	remaining: 567ms
219:	learn: 0.0343226	total: 687ms	remaining: 562ms
220:	learn: 0.0340435	total: 693ms	remaining: 562ms
221:	learn: 0.0338081	total: 698ms	remaining: 559ms
222:	learn: 0.0335764	total: 699ms	remaining: 555ms
223:	learn: 0.0334452	total: 705ms	remaining: 554ms
224:	learn: 0.0334045	total: 710ms	remaining: 552ms
225:	learn: 0.0331575	total: 715ms	remaining: 550ms
226:	learn: 0.0328833	total: 723ms	remaining: 551ms
227:	learn: 0.0327983	total: 724ms	remaining: 546ms
228:	learn: 0.0327517	total: 730ms	remaining: 545ms
229:	learn: 0.0323833	total: 731ms	remaining: 540ms
230:	learn: 0.0323379	total: 732ms	remaining: 536ms
231:	learn: 0.0320538	total: 741ms	remaining: 537ms
232:	learn: 0.0319286	total: 742ms	remaining: 532ms
233:	learn: 0.0317869	total: 752ms	remaining: 533ms
234:	learn: 0.0316938	total: 761ms	remaining: 534ms
235:	learn: 0.0315323	total: 762ms	remaining: 529ms
236:	learn: 0.0313695	total: 768ms	remaining: 528ms
237:	learn: 0.0311536	total: 773ms	remaining: 526ms
238:	learn: 0.0310953	total: 776ms	remaining: 523ms
239:	learn: 0.0310423	total: 781ms	remaining: 521ms
240:	learn: 0.0308990	total: 782ms	remaining: 516ms
241:	learn: 0.0306792	total: 783ms	remaining: 511ms
242:	learn: 0.0305831	total: 788ms	remaining: 509ms
243:	learn: 0.0303256	total: 789ms	remaining: 505ms
244:	learn: 0.0302626	total: 795ms	remaining: 503ms
245:	learn: 0.0301039	total: 799ms	remaining: 500ms
246:	learn: 0.0299010	total: 800ms	remaining: 496ms
247:	learn: 0.0295261	total: 807ms	remaining: 494ms
248:	learn: 0.0292752	total: 808ms	remaining: 490ms
249:	learn: 0.0289847	total: 808ms	remaining: 485ms
250:	learn: 0.0288853	total: 809ms	remaining: 480ms
251:	learn: 0.0287065	total: 812ms	remaining: 477ms
252:	learn: 0.0286178	total: 813ms	remaining: 473ms
253:	learn: 0.0285423	total: 814ms	remaining: 468ms
254:	learn: 0.0284149	total: 818ms	remaining: 465ms
255:	learn: 0.0281782	total: 819ms	remaining: 461ms
256:	learn: 0.0280260	total: 824ms	remaining: 459ms
257:	learn: 0.0279803	total: 826ms	remaining: 454ms
258:	learn: 0.0278859	total: 831ms	remaining: 452ms
259:	learn: 0.0278573	total: 836ms	remaining: 450ms
260:	learn: 0.0276425	total: 837ms	remaining: 446ms
261:	learn: 0.0274348	total: 841ms	remaining: 443ms
262:	learn: 0.0271890	total: 841ms	remaining: 438ms
263:	learn: 0.0270307	total: 846ms	remaining: 436ms
264:	learn: 0.0268667	total: 847ms	remaining: 432ms
265:	learn: 0.0267573	total: 852ms	remaining: 429ms
266:	learn: 0.0267053	total: 853ms	remaining: 425ms
267:	learn: 0.0265903	total: 858ms	remaining: 423ms
268:	learn: 0.0265482	total: 863ms	remaining: 420ms
269:	learn: 0.0264220	total: 864ms	remaining: 416ms
270:	learn: 0.0263664	total: 869ms	remaining: 414ms
271:	learn: 0.0262968	total: 873ms	remaining: 411ms
272:	learn: 0.0262707	total: 878ms	remaining: 408ms
273:	learn: 0.0262442	total: 879ms	remaining: 404ms
274:	learn: 0.0262204	total: 884ms	remaining: 402ms
275:	learn: 0.0261496	total: 885ms	remaining: 398ms
276:	learn: 0.0260980	total: 890ms	remaining: 395ms
277:	learn: 0.0259909	total: 897ms	remaining: 394ms
278:	learn: 0.0258884	total: 898ms	remaining: 390ms
279:	learn: 0.0256922	total: 905ms	remaining: 388ms
280:	learn: 0.0254690	total: 906ms	remaining: 384ms
281:	learn: 0.0251941	total: 913ms	remaining: 382ms
282:	learn: 0.0250214	total: 914ms	remaining: 378ms
283:	learn: 0.0248895	total: 921ms	remaining: 376ms
284:	learn: 0.0248441	total: 928ms	remaining: 375ms
285:	learn: 0.0247546	total: 929ms	remaining: 370ms
286:	learn: 0.0247229	total: 936ms	remaining: 369ms
287:	learn: 0.0246863	total: 937ms	remaining: 365ms
288:	learn: 0.0245921	total: 944ms	remaining: 363ms
289:	learn: 0.0244515	total: 952ms	remaining: 361ms
290:	learn: 0.0241286	total: 953ms	remaining: 357ms
291:	learn: 0.0239733	total: 960ms	remaining: 355ms
292:	learn: 0.0238955	total: 961ms	remaining: 351ms
293:	learn: 0.0238118	total: 968ms	remaining: 349ms
294:	learn: 0.0237484	total: 973ms	remaining: 346ms
295:	learn: 0.0236798	total: 974ms	remaining: 342ms
296:	learn: 0.0235212	total: 979ms	remaining: 339ms
297:	learn: 0.0233888	total: 980ms	remaining: 335ms
298:	learn: 0.0231663	total: 985ms	remaining: 333ms
299:	learn: 0.0230763	total: 986ms	remaining: 329ms
300:	learn: 0.0230361	total: 993ms	remaining: 326ms
301:	learn: 0.0228804	total: 997ms	remaining: 324ms
302:	learn: 0.0227280	total: 999ms	remaining: 320ms
303:	learn: 0.0227065	total: 1s	remaining: 316ms
304:	learn: 0.0225876	total: 1s	remaining: 312ms
305:	learn: 0.0224595	total: 1s	remaining: 308ms
306:	learn: 0.0224207	total: 1.01s	remaining: 305ms
307:	learn: 0.0222829	total: 1.01s	remaining: 301ms
308:	learn: 0.0220755	total: 1.01s	remaining: 299ms
309:	learn: 0.0219869	total: 1.01s	remaining: 295ms
310:	learn: 0.0219714	total: 1.02s	remaining: 293ms
311:	learn: 0.0219465	total: 1.02s	remaining: 289ms
312:	learn: 0.0218612	total: 1.03s	remaining: 287ms
313:	learn: 0.0217347	total: 1.03s	remaining: 283ms
314:	learn: 0.0217084	total: 1.04s	remaining: 280ms
315:	learn: 0.0216524	total: 1.04s	remaining: 276ms
316:	learn: 0.0215585	total: 1.05s	remaining: 274ms
317:	learn: 0.0215390	total: 1.05s	remaining: 270ms
318:	learn: 0.0215113	total: 1.05s	remaining: 266ms
319:	learn: 0.0213829	total: 1.06s	remaining: 264ms
320:	learn: 0.0213270	total: 1.06s	remaining: 260ms
321:	learn: 0.0212810	total: 1.06s	remaining: 258ms
322:	learn: 0.0211723	total: 1.07s	remaining: 254ms
323:	learn: 0.0211490	total: 1.07s	remaining: 250ms
324:	learn: 0.0210162	total: 1.07s	remaining: 248ms
325:	learn: 0.0209710	total: 1.07s	remaining: 244ms
326:	learn: 0.0208441	total: 1.08s	remaining: 242ms
327:	learn: 0.0208024	total: 1.08s	remaining: 238ms
328:	learn: 0.0207693	total: 1.09s	remaining: 235ms
329:	learn: 0.0207536	total: 1.1s	remaining: 233ms
330:	learn: 0.0206967	total: 1.1s	remaining: 229ms
331:	learn: 0.0205964	total: 1.1s	remaining: 226ms
332:	learn: 0.0203754	total: 1.11s	remaining: 223ms
333:	learn: 0.0203412	total: 1.11s	remaining: 220ms
334:	learn: 0.0203238	total: 1.11s	remaining: 216ms
335:	learn: 0.0201572	total: 1.12s	remaining: 214ms
336:	learn: 0.0200207	total: 1.13s	remaining: 212ms
337:	learn: 0.0199051	total: 1.14s	remaining: 208ms
338:	learn: 0.0198707	total: 1.15s	remaining: 206ms
339:	learn: 0.0197884	total: 1.15s	remaining: 203ms
340:	learn: 0.0197417	total: 1.15s	remaining: 200ms
341:	learn: 0.0196646	total: 1.16s	remaining: 197ms
342:	learn: 0.0195580	total: 1.16s	remaining: 194ms
343:	learn: 0.0195495	total: 1.19s	remaining: 193ms
344:	learn: 0.0194909	total: 1.19s	remaining: 190ms
345:	learn: 0.0194411	total: 1.2s	remaining: 188ms
346:	learn: 0.0193752	total: 1.21s	remaining: 184ms
347:	learn: 0.0193264	total: 1.22s	remaining: 182ms
348:	learn: 0.0193047	total: 1.22s	remaining: 178ms
349:	learn: 0.0192565	total: 1.22s	remaining: 174ms
350:	learn: 0.0192364	total: 1.22s	remaining: 170ms
351:	learn: 0.0191972	total: 1.22s	remaining: 167ms
352:	learn: 0.0191480	total: 1.22s	remaining: 163ms
353:	learn: 0.0189726	total: 1.23s	remaining: 160ms
354:	learn: 0.0189072	total: 1.23s	remaining: 156ms
355:	learn: 0.0187738	total: 1.23s	remaining: 152ms
356:	learn: 0.0187529	total: 1.23s	remaining: 149ms
357:	learn: 0.0186543	total: 1.24s	remaining: 145ms
358:	learn: 0.0186013	total: 1.24s	remaining: 141ms
359:	learn: 0.0185440	total: 1.24s	remaining: 138ms
360:	learn: 0.0184370	total: 1.24s	remaining: 134ms
361:	learn: 0.0183846	total: 1.24s	remaining: 131ms
362:	learn: 0.0183030	total: 1.25s	remaining: 127ms
363:	learn: 0.0182783	total: 1.25s	remaining: 123ms
364:	learn: 0.0181957	total: 1.25s	remaining: 120ms
365:	learn: 0.0181055	total: 1.26s	remaining: 117ms
366:	learn: 0.0180395	total: 1.26s	remaining: 114ms
367:	learn: 0.0179850	total: 1.27s	remaining: 110ms
368:	learn: 0.0179218	total: 1.27s	remaining: 107ms
369:	learn: 0.0179012	total: 1.28s	remaining: 104ms
370:	learn: 0.0177997	total: 1.28s	remaining: 100ms
371:	learn: 0.0177477	total: 1.28s	remaining: 96.7ms
372:	learn: 0.0176963	total: 1.29s	remaining: 93.3ms
373:	learn: 0.0176636	total: 1.29s	remaining: 89.7ms
374:	learn: 0.0176206	total: 1.29s	remaining: 86.1ms
375:	learn: 0.0175828	total: 1.3s	remaining: 82.7ms
376:	learn: 0.0175235	total: 1.3s	remaining: 79.2ms
377:	learn: 0.0174483	total: 1.3s	remaining: 75.8ms
378:	learn: 0.0174307	total: 1.3s	remaining: 72.2ms
379:	learn: 0.0173895	total: 1.3s	remaining: 68.7ms
380:	learn: 0.0172977	total: 1.31s	remaining: 65.3ms
381:	learn: 0.0172744	total: 1.31s	remaining: 61.8ms
382:	learn: 0.0171881	total: 1.31s	remaining: 58.4ms
383:	learn: 0.0171274	total: 1.32s	remaining: 54.9ms
384:	learn: 0.0170763	total: 1.32s	remaining: 51.3ms
385:	learn: 0.0169856	total: 1.32s	remaining: 48ms

CatBoostClassifier(depth=3, iterations=400, learning_rate=0.1)

In [ ]:
model_prediction_cb = model_cb.predict(X_test)
print('Accuracy Score CatBoost Model is:', round(accuracy_score(model_prediction_cb, y_test)*100,2),'%')

Accuracy Score CatBoost Model is: 93.58 %

In [ ]:
# data = [[1,2,3,4,5]]
# new_df = pd.DataFrame(data, columns=[
#     'radius_mean', 'texture_mean', 'perimeter_mean',
#     'smoothness_mean', 'compactness_mean'
# ])

# single = model_rf.predict(new_df)
# proba = model_rf.predict_proba(new_df)

# if single==1:
#   output = 'The patient is diagnosed with Breast Cancer'
#   output1 = 'Confidence: {}'.format(proba*100)
# else:
#   output = 'The patient is not diagnosed with Breast Cancer'
#   output1 = ''


# print(output+output1)

In [ ]:
data = [[11.77, 14.78, 138.5, 0.1076, 0.1842]]
new_df = pd.DataFrame(data, columns=[
    'radius_mean', 'texture_mean', 'perimeter_mean',
    'smoothness_mean', 'compactness_mean'
])

single = model_cb.predict(new_df)
proba = model_cb.predict_proba(new_df)[:,1]

if single==1:
  output = 'The patient is diagnosed with Breast Cancer'
  output1 = 'Confidence: {}'.format(proba*100)
else:
  output = 'The patient is not diagnosed with Breast Cancer'
  output1 = ''


print(output+output1)

The patient is diagnosed with Breast CancerConfidence: [70.56601116]